
import React, { useState } from 'react';
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { 
  BarChart3, 
  FileText, 
  ListFilter,
  Clock,
  PlusCircle,
  Calendar,
  ArrowUpRight
} from 'lucide-react';
import StandardReports from './StandardReports';
import CustomReports from './CustomReports';
import ScheduledReports from './ScheduledReports';
import SavedReports from './SavedReports';
import { EnhancedCard, EnhancedCardContent } from '@/components/ui/enhanced-card';

const ReportsModule = () => {
  const [activeTab, setActiveTab] = useState('standard');

  const handleTabChange = (value: string) => {
    setActiveTab(value);
  };

  const reportStats = [
    { title: "Reports Available", value: "42", icon: FileText, gradient: "blue" as const, iconBg: "bg-blue-100", iconColor: "text-blue-600" },
    { title: "Reports Generated (Month)", value: "156", icon: BarChart3, gradient: "green" as const, iconBg: "bg-green-100", iconColor: "text-green-600" },
    { title: "Scheduled Reports", value: "8", icon: Clock, gradient: "purple" as const, iconBg: "bg-purple-100", iconColor: "text-purple-600" },
    { title: "Saved Reports", value: "15", icon: Calendar, gradient: "orange" as const, iconBg: "bg-orange-100", iconColor: "text-orange-600" },
  ];
  
  return (
    <div className="space-y-6">
      {/* Stats Cards - Fixed sizing and consistent layout */}
      <div className="grid gap-4 grid-cols-1 sm:grid-cols-2 lg:grid-cols-4">
        {reportStats.map((stat, index) => (
          <EnhancedCard key={index} gradient={stat.gradient} className="shadow-sm hover:shadow-md transition-shadow">
            <EnhancedCardContent className="p-4 flex items-center space-x-4">
              <div className={`rounded-full p-3 ${stat.iconBg}`}>
                <stat.icon className={`h-6 w-6 ${stat.iconColor}`} />
              </div>
              <div>
                <p className="text-sm font-medium text-muted-foreground">{stat.title}</p>
                <h3 className="text-2xl font-bold text-gray-800">{stat.value}</h3>
              </div>
            </EnhancedCardContent>
          </EnhancedCard>
        ))}
      </div>
      
      {/* Report Activity Summary - Fixed height and overflow issues */}
      <div className="grid grid-cols-1 lg:grid-cols-3 gap-4">
        <Card className="lg:col-span-2 shadow-sm border-nimms-primary/10">
          <CardHeader className="pb-2">
            <CardTitle className="text-lg font-medium flex items-center justify-between">
              Report Generation Activity
              <span className="text-sm text-muted-foreground font-normal">Last 30 days</span>
            </CardTitle>
          </CardHeader>
          <CardContent className="p-4">
            <div className="h-[250px] w-full flex items-center justify-center bg-muted/20 rounded-md">
              <div className="text-center">
                <BarChart3 className="h-10 w-10 text-muted-foreground/50 mx-auto mb-2" />
                <p className="text-muted-foreground">Activity chart will appear here</p>
              </div>
            </div>
          </CardContent>
        </Card>

        <Card className="shadow-sm border-nimms-primary/10">
          <CardHeader className="pb-2">
            <CardTitle className="text-lg font-medium">Recent Activity</CardTitle>
          </CardHeader>
          <CardContent className="p-4">
            <div className="space-y-4">
              {[1, 2, 3].map((item) => (
                <div key={item} className="flex items-center gap-3 border-b border-border pb-3 last:border-0 last:pb-0">
                  <div className="bg-primary/10 p-2 rounded-full">
                    <FileText className="h-4 w-4 text-primary" />
                  </div>
                  <div className="flex-1 min-w-0">
                    <p className="text-sm font-medium truncate">Mortgage Performance Report</p>
                    <p className="text-xs text-muted-foreground">Generated by Ahmed Ibrahim</p>
                  </div>
                  <span className="text-xs text-muted-foreground whitespace-nowrap">2h ago</span>
                </div>
              ))}
              <div className="pt-2">
                <a href="#" className="text-sm text-primary flex items-center">
                  View all activities
                  <ArrowUpRight className="h-3 w-3 ml-1" />
                </a>
              </div>
            </div>
          </CardContent>
        </Card>
      </div>
      
      {/* Main Reports Interface - Better constrained content */}
      <Card className="shadow-sm border-nimms-primary/10">
        <CardHeader>
          <CardTitle className="text-lg font-medium">Reports Center</CardTitle>
          <CardDescription>
            Generate, customize, and schedule reports for various stakeholders
          </CardDescription>
        </CardHeader>
        <CardContent>
          <Tabs value={activeTab} onValueChange={handleTabChange} className="w-full">
            <TabsList className="mb-4 grid grid-cols-4 w-full md:w-auto">
              <TabsTrigger value="standard" className="text-sm">Standard Reports</TabsTrigger>
              <TabsTrigger value="custom" className="text-sm">Custom Reports</TabsTrigger>
              <TabsTrigger value="scheduled" className="text-sm">Scheduled</TabsTrigger>
              <TabsTrigger value="saved" className="text-sm">Saved Reports</TabsTrigger>
            </TabsList>
            
            <div className="pt-2">
              <TabsContent value="standard">
                <StandardReports />
              </TabsContent>
              
              <TabsContent value="custom">
                <CustomReports />
              </TabsContent>
              
              <TabsContent value="scheduled">
                <ScheduledReports />
              </TabsContent>
              
              <TabsContent value="saved">
                <SavedReports />
              </TabsContent>
            </div>
          </Tabs>
        </CardContent>
      </Card>
    </div>
  );
};

export default ReportsModule;
